---
# This playbook deploys the whole application stack in this site.

- name: Aplicar configuración comúnes a todos los nodos.
  hosts: all
  become: yes

  roles:
    - common

- name: Instalar/configurar el servidor web y la aplicación.
  hosts: webservers
  become: yes

  roles:
    - web

- name: Instalar/configurar el motor de BBDD.
  hosts: dbservers
  become: yes

  roles:
    - db
